/*

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/
module derelict.allegro5.dialog;

private {
    import derelict.util.loader,
           derelict.util.system;

    import derelict.allegro5.internal,
           derelict.allegro5.types;

    enum libNames = genLibNames("Dialog");
}

struct ALLEGRO_FILECHOOSER;
struct ALLEGRO_TEXTLOG;
struct ALLEGRO_MENU;

struct ALLEGRO_MENU_INFO {
    const(char)* caption;
    ushort id;
    int flags;
    ALLEGRO_BITMAP* icon;
}

enum {
   ALLEGRO_FILECHOOSER_FILE_MUST_EXIST = 1,
   ALLEGRO_FILECHOOSER_SAVE = 2,
   ALLEGRO_FILECHOOSER_FOLDER = 4,
   ALLEGRO_FILECHOOSER_PICTURES = 8,
   ALLEGRO_FILECHOOSER_SHOW_HIDDEN = 16,
   ALLEGRO_FILECHOOSER_MULTIPLE = 32
}

enum {
   ALLEGRO_MESSAGEBOX_WARN = 1<<0,
   ALLEGRO_MESSAGEBOX_ERROR = 1<<1,
   ALLEGRO_MESSAGEBOX_OK_CANCEL = 1<<2,
   ALLEGRO_MESSAGEBOX_YES_NO = 1<<3,
   ALLEGRO_MESSAGEBOX_QUESTION = 1<<4
}

enum {
   ALLEGRO_TEXTLOG_NO_CLOSE = 1<<0,
   ALLEGRO_TEXTLOG_MONOSPACE = 1<<1
}

enum {
   ALLEGRO_EVENT_NATIVE_DIALOG_CLOSE = 600
}

extern(C) @nogc nothrow {
    alias da_al_init_native_dialog_addon = bool function();
    alias da_al_shutdown_native_dialog_addon = void function();
    alias da_al_create_native_file_dialog = ALLEGRO_FILECHOOSER* function(const(char)*, const(char)*, const(char)*, int);
    alias da_al_show_native_file_dialog = bool function(ALLEGRO_DISPLAY*, ALLEGRO_FILECHOOSER*);
    alias da_al_get_native_file_dialog_count = int function(const(ALLEGRO_FILECHOOSER)*);
    alias da_al_get_native_file_dialog_path = const(char)* function(const(ALLEGRO_FILECHOOSER)*, size_t);
    alias da_al_destroy_native_file_dialog = void function(ALLEGRO_FILECHOOSER*);
    alias da_al_show_native_message_box = int function(ALLEGRO_DISPLAY*, const(char)*, const(char)*, const(char)*, const(char)*, int);
    alias da_al_open_native_text_log = ALLEGRO_TEXTLOG* function(const(char)*, int);
    alias da_al_close_native_text_log = void function(ALLEGRO_TEXTLOG*);
    alias da_al_append_native_text_log = void function(ALLEGRO_TEXTLOG*, const(char)*, ...);
    alias da_al_get_native_text_log_event_source = ALLEGRO_EVENT_SOURCE* function(ALLEGRO_TEXTLOG*);
    alias da_al_get_allegro_native_dialog_version = uint function();
}

__gshared {
    da_al_init_native_dialog_addon al_init_native_dialog_addon;
    da_al_shutdown_native_dialog_addon al_shutdown_native_dialog_addon;
    da_al_create_native_file_dialog al_create_native_file_dialog;
    da_al_show_native_file_dialog al_show_native_file_dialog;
    da_al_get_native_file_dialog_count al_get_native_file_dialog_count;
    da_al_get_native_file_dialog_path al_get_native_file_dialog_path;
    da_al_destroy_native_file_dialog al_destroy_native_file_dialog;
    da_al_show_native_message_box al_show_native_message_box;
    da_al_open_native_text_log al_open_native_text_log;
    da_al_close_native_text_log al_close_native_text_log;
    da_al_append_native_text_log al_append_native_text_log;
    da_al_get_native_text_log_event_source al_get_native_text_log_event_source;
    da_al_get_allegro_native_dialog_version al_get_allegro_native_dialog_version;
}

class DerelictAllegro5DialogLoader : SharedLibLoader {
    public this() {
        super(libNames);
    }

    protected override void loadSymbols() {
        bindFunc(cast(void**)&al_init_native_dialog_addon, "al_init_native_dialog_addon");
        bindFunc(cast(void**)&al_shutdown_native_dialog_addon, "al_shutdown_native_dialog_addon");
        bindFunc(cast(void**)&al_create_native_file_dialog, "al_create_native_file_dialog");
        bindFunc(cast(void**)&al_show_native_file_dialog, "al_show_native_file_dialog");
        bindFunc(cast(void**)&al_get_native_file_dialog_count, "al_get_native_file_dialog_count");
        bindFunc(cast(void**)&al_get_native_file_dialog_path, "al_get_native_file_dialog_path");
        bindFunc(cast(void**)&al_destroy_native_file_dialog, "al_destroy_native_file_dialog");
        bindFunc(cast(void**)&al_show_native_message_box, "al_show_native_message_box");
        bindFunc(cast(void**)&al_open_native_text_log, "al_open_native_text_log");
        bindFunc(cast(void**)&al_close_native_text_log, "al_close_native_text_log");
        bindFunc(cast(void**)&al_append_native_text_log, "al_append_native_text_log");
        bindFunc(cast(void**)&al_get_native_text_log_event_source, "al_get_native_text_log_event_source");
        bindFunc(cast(void**)&al_get_allegro_native_dialog_version, "al_get_allegro_native_dialog_version");
    }
}

__gshared DerelictAllegro5DialogLoader DerelictAllegro5Dialog;

shared static this() {
    DerelictAllegro5Dialog = new DerelictAllegro5DialogLoader;
}